import type { Metadata } from 'next'
import { Roboto, Suez_One } from 'next/font/google'
import './globals.css'

const robotoFont = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
})

const suezOneFont = Suez_One({
  variable: '--font-suez-one',
  subsets: ['latin'],
  weight: ['400'],
})

export const metadata: Metadata = {
  title: 'Kevs Dev',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${robotoFont.variable} ${suezOneFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
