import type { Metadata } from 'next'
import { Roboto, Suez_One } from 'next/font/google'
import { Toaster } from '@/components/ui/sonner'
import './globals.css'
import { Analytics } from '@vercel/analytics/next'
import Cursor from '@/components/Cursor'

const robotoFont = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
})

const suezOneFont = Suez_One({
  variable: '--font-suez-one',
  subsets: ['latin'],
  weight: ['400'],
})

export const metadata: Metadata = {
  title: 'Kevs Dev',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${robotoFont.variable} ${suezOneFont.variable} antialiased`}
      >
        {children}
        <Toaster position='top-center' />
        <Analytics />
        <Cursor />
      </body>
    </html>
  )
}
